CREATE DATABASE IF NOT EXISTS Handyman;

USE Handyman;

CREATE TABLE IF NOT EXISTS Person (
    id INTEGER PRIMARY KEY, #AUTO_INCREMENT,
    name VARCHAR(31) NOT NULL,
    surname VARCHAR(31) NOT NULL,
    email VARCHAR(31) CHECK ( email REGEXP '^[A-Za-z0-9.!?_%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$') ,
    password VARCHAR(31) NOT NULL CHECK ( LENGTH(password)>=8 ),
    username VARCHAR(31) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Client(
    id INTEGER PRIMARY KEY,
    address VARCHAR(51),
    CONSTRAINT FK_ClientPerson FOREIGN KEY (id) REFERENCES Person(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Worker(
    id INTEGER PRIMARY KEY,
    phoneNumber VARCHAR(13) NOT NULL DEFAULT '+381641234567',
    CONSTRAINT FK_WorkerPerson FOREIGN KEY (id) REFERENCES Person(id) ON DELETE CASCADE
);

